version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./tmp:/home/node/app/tmp
    restart: always
